### ISSUE TITLE
建图和重定位问题

### ISSUE THREAD

**Issue by Raidenzheng** [shallowlife/SC-LIO-SAM_relocalization#3]
您的代码仅能用于重定位吗？我在重定位之前，需要先运行SC_LIO_SAM建图。我用的也是Hesai/pandarXT16激光雷达。那么我建图时，跑SC_LIO_SAM需要修改哪些参数和代码呢？我看他的激光仅支持'velodyne' or 'ouster' or 'mulran'。您当初建图的时候，用的是什么方法？

另外，您的代码支持建图吗？

**Comment by Raidenzheng** [comment]
我跑通了，牛，效果不错

**Comment by shallowlife** [comment]
行的，祝你成功
